// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VehicleTracker.Api.Data;

#nullable disable

namespace VehicleTracker.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260106121441_AddUserTable")]
    partial class AddUserTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VehicleTracker.Api.Models.Driver", b =>
                {
                    b.Property<int>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("driver_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DriverId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("license_number");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("phone_number");

                    b.HasKey("DriverId");

                    b.HasIndex("LicenseNumber")
                        .IsUnique();

                    b.ToTable("driver");
                });

            modelBuilder.Entity("VehicleTracker.Api.Models.Incident", b =>
                {
                    b.Property<int>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("incident_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IncidentId"));

                    b.Property<int?>("AssignedTo")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_to");

                    b.Property<int?>("IncidentStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("incident_status_id");

                    b.Property<int?>("IncidentTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("incident_type_id");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("location");

                    b.HasKey("IncidentId");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("IncidentStatusId");

                    b.HasIndex("IncidentTypeId");

                    b.ToTable("incident");
                });

            modelBuilder.Entity("VehicleTracker.Api.Models.IncidentStatus", b =>
                {
                    b.Property<int>("IncidentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("incident_status_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IncidentStatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status_name");

                    b.HasKey("IncidentStatusId");

                    b.ToTable("incident_status");
                });

            modelBuilder.Entity("VehicleTracker.Api.Models.IncidentType", b =>
                {
                    b.Property<int>("IncidentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("incident_type_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IncidentTypeId"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type_name");

                    b.HasKey("IncidentTypeId");

                    b.ToTable("incident_type");
                });

            modelBuilder.Entity("VehicleTracker.Api.Models.LocationHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Fuel")
                        .HasColumnType("numeric")
                        .HasColumnName("fuel");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("location");

                    b.Property<decimal?>("Speed")
                        .HasColumnType("numeric")
                        .HasColumnName("speed");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("location_history");
                });

            modelBuilder.Entity("VehicleTracker.Api.Models.RealTimeData", b =>
                {
                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.Property<decimal?>("CurrentFuel")
                        .HasColumnType("numeric")
                        .HasColumnName("current_fuel");

                    b.Property<Point>("CurrentLocation")
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("current_location");

                    b.Property<decimal?>("CurrentSpeed")
                        .HasColumnType("numeric")
                        .HasColumnName("current_speed");

                    b.Property<Guid?>("VehicleStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_status_id");

                    b.HasKey("VehicleId");

                    b.HasIndex("VehicleStatusId");

                    b.ToTable("real_time_data");
                });

            modelBuilder.Entity("VehicleTracker.Api.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("user");
                });

            modelBuilder.Entity("VehicleTracker.Api.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VehicleId"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("color");

                    b.Property<int?>("DriverId")
                        .HasColumnType("integer")
                        .HasColumnName("driver_id");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("make");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("plate_number");

                    b.HasKey("VehicleId");

                    b.HasIndex("DriverId");

                    b.HasIndex("PlateNumber")
                        .IsUnique();

                    b.ToTable("vehicle");
                });

            modelBuilder.Entity("VehicleTracker.Api.Models.VehicleStatus", b =>
                {
                    b.Property<Guid>("VehicleStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_status_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("VehicleStatusId");

                    b.ToTable("vehicle_status");
                });

            modelBuilder.Entity("VehicleTracker.Api.Models.Incident", b =>
                {
                    b.HasOne("VehicleTracker.Api.Models.Vehicle", "AssignedVehicle")
                        .WithMany("AssignedIncidents")
                        .HasForeignKey("AssignedTo");

                    b.HasOne("VehicleTracker.Api.Models.IncidentStatus", "IncidentStatus")
                        .WithMany("Incidents")
                        .HasForeignKey("IncidentStatusId");

                    b.HasOne("VehicleTracker.Api.Models.IncidentType", "IncidentType")
                        .WithMany("Incidents")
                        .HasForeignKey("IncidentTypeId");

                    b.Navigation("AssignedVehicle");

                    b.Navigation("IncidentStatus");

                    b.Navigation("IncidentType");
                });

            modelBuilder.Entity("VehicleTracker.Api.Models.LocationHistory", b =>
                {
                    b.HasOne("VehicleTracker.Api.Models.RealTimeData", "RealTimeData")
                        .WithMany("LocationHistory")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RealTimeData");
                });

            modelBuilder.Entity("VehicleTracker.Api.Models.RealTimeData", b =>
                {
                    b.HasOne("VehicleTracker.Api.Models.Vehicle", "Vehicle")
                        .WithOne()
                        .HasForeignKey("VehicleTracker.Api.Models.RealTimeData", "VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleTracker.Api.Models.VehicleStatus", "VehicleStatus")
                        .WithMany()
                        .HasForeignKey("VehicleStatusId");

                    b.Navigation("Vehicle");

                    b.Navigation("VehicleStatus");
                });

            modelBuilder.Entity("VehicleTracker.Api.Models.Vehicle", b =>
                {
                    b.HasOne("VehicleTracker.Api.Models.Driver", "Driver")
                        .WithMany("Vehicles")
                        .HasForeignKey("DriverId");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("VehicleTracker.Api.Models.Driver", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("VehicleTracker.Api.Models.IncidentStatus", b =>
                {
                    b.Navigation("Incidents");
                });

            modelBuilder.Entity("VehicleTracker.Api.Models.IncidentType", b =>
                {
                    b.Navigation("Incidents");
                });

            modelBuilder.Entity("VehicleTracker.Api.Models.RealTimeData", b =>
                {
                    b.Navigation("LocationHistory");
                });

            modelBuilder.Entity("VehicleTracker.Api.Models.Vehicle", b =>
                {
                    b.Navigation("AssignedIncidents");
                });
#pragma warning restore 612, 618
        }
    }
}
